sprint:
  datasource:
    url: jdbc:postgres://localhost:5432/trinity
    username: root
    password: root
    driverClassName: com.postgres.jdbc.Driver

  mybatis:
    mapper-locations: classpath*:/mybatis/mapper/*.xml
    type-aliases-package: com.exapmle.mybatisdemo.model
    configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
      cache-enabled: false